[package]
name = "tgs"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Kirill Svirid <svirid-kirill97@yandex.ru>"]
description = "Template for styling technical documents according to GOST standards"
repository = "https://github.com/typst-g7-32/modern-g7-32"
keywords = ["gost", "technical", "document", "russian"]
categories = [ "components", "scripting", "model"]
disciplines = ["engineering","design"]
compiler = "0.13.1"
exclude = [".github", "docs", "tests", "assets"]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = ""

