[gost_r_8_563_2009_test]
type = "normative"
name = "ГОСТ Р 8.563"
year = 2009
title = "Разработка и постановка на производство составных частей активных зон объектов использования атомной энергии и оценка их соответствия в форме испытаний. Порядок проведения"

[gost_r_15_011]
type = "normative"
name = "ГОСТ Р 15.011"
year = 96
title = "Система разработки и постановки продукции на производство. Патентные исследования. Содержание и порядок проведения"

[gost_r_iso_9000]
type = "normative"
name = "ГОСТ Р ИСО 9000"
year = 2015
title = "Национальный стандарт Российской Федерации. Системы менеджмента и качества. Основные положения и словарь"

[gost_r_iso_9001]
title = "Национальный стандарт Российской Федерации. Системы менеджмента и качества. Требования"
type = "normative"
name = "ГОСТ Р ИСО 9001"
year = 2015
